import crypto from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import cors from 'cors';
import express from 'express';
import helmet from 'helmet';
import jwt from 'jsonwebtoken';
import { z } from 'zod';

const app = express();
const PORT = Number(process.env.PORT || 8787);
const SECRET = process.env.JWT_SECRET || 'change-this-local-development-secret-before-deploying';
const DATA_FILE = path.resolve(process.cwd(), 'data/transactions.json');
const ACTION_FILE = path.resolve(process.cwd(), 'data/case-actions.json');
const WEIGHTS = { price_deviation: .30, duplicate_similarity: .20, vendor_concentration: .20, purchase_pattern: .15, timing_anomaly: .10, approval_velocity: .05 };
const credentials = { departmentId: process.env.DEMO_DEPARTMENT_ID || 'PWD-MH-204', officerId: process.env.DEMO_OFFICER_ID || 'AUD-ASH-204', password: process.env.DEMO_PASSWORD || 'GovSpend@2026' };
let transactions = [];
let actions = [];
let audit = [];
const digest = value => crypto.createHash('sha256').update(String(value)).digest('hex');
const money = value => Number(value || 0);
const vendorToken = vendor => `VEND-${crypto.createHmac('sha256', SECRET).update(vendor).digest('hex').slice(0, 8).toUpperCase()}`;
const median = values => { const sorted = values.filter(Number.isFinite).sort((a,b)=>a-b); if (!sorted.length) return 0; const middle = Math.floor(sorted.length / 2); return sorted.length % 2 ? sorted[middle] : (sorted[middle - 1] + sorted[middle]) / 2; };
const record = (actor, action, resource, payload = {}) => { const previousHash = audit.at(-1)?.entryHash || '0'.repeat(64); const timestamp = new Date().toISOString(); const payloadHash = digest(JSON.stringify(payload)); const entryHash = digest(`${previousHash}|${actor}|${action}|${resource}|${payloadHash}|${timestamp}`); const entry = { id:`LOG-${String(audit.length+1).padStart(5,'0')}`, previousHash, entryHash, actor, action, resource, payloadHash, timestamp }; audit.push(entry); return entry; };
const load = async () => { const content = JSON.parse(await readFile(DATA_FILE, 'utf8')); transactions = content.transactions || []; try { actions = JSON.parse(await readFile(ACTION_FILE, 'utf8')); } catch { actions = []; } };
const persistActions = async () => { try { await writeFile(ACTION_FILE, JSON.stringify(actions, null, 2)); } catch { /* serverless environments keep actions for request lifetime only */ } };
const daysApart = (a,b) => Math.abs(new Date(a).getTime() - new Date(b).getTime()) / 86400000;
const signalsFor = tx => {
  const peers = transactions.filter(item => item.id !== tx.id && item.category === tx.category && item.region === tx.region);
  const peerPrices = peers.map(item => money(item.unitPrice)); const peerMedian = median(peerPrices); const priceRatio = peerMedian ? tx.unitPrice / peerMedian : 1;
  const vendorRows = transactions.filter(item => item.department === tx.department); const departmentSpend = vendorRows.reduce((sum,item)=>sum+money(item.amount),0); const vendorSpend = vendorRows.filter(item=>item.vendor===tx.vendor).reduce((sum,item)=>sum+money(item.amount),0); const concentration = departmentSpend ? vendorSpend / departmentSpend : 0;
  const similar = transactions.filter(item => item.id !== tx.id && item.vendor === tx.vendor && (item.referenceGroup === tx.referenceGroup || (Math.abs(money(item.amount)-money(tx.amount)) / Math.max(1,money(tx.amount)) < .02 && daysApart(item.date,tx.date) <= 30))).length;
  const clustered = transactions.filter(item => item.id !== tx.id && item.vendor === tx.vendor && item.department === tx.department && daysApart(item.date,tx.date) <= 14 && money(item.amount) < 500000).reduce((sum,item)=>sum+money(item.amount),0);
  const approvalMedian = median(peers.map(item=>money(item.approvalHours))) || 48;
  return [
    { type:'price_deviation', label:'Price deviation', value:Math.min(1,Math.max(0,(priceRatio-1.25)/1.45)), confidence:Math.min(1,.35+peers.length/100), evidenceId:'EV-PRICE', detail:`Unit price is ${priceRatio.toFixed(1)}× the peer median.` },
    { type:'duplicate_similarity', label:'Duplicate similarity', value:similar ? Math.min(1,.82+similar*.06) : 0, confidence:similar ? .92 : .70, evidenceId:'EV-DUP', detail:similar ? `${similar} similar authorised record(s) found in the comparison window.` : 'No matching invoice pattern found.' },
    { type:'vendor_concentration', label:'Vendor concentration', value:Math.min(1,concentration/.70), confidence:.94, evidenceId:'EV-GRAPH', detail:`Masked vendor represents ${(concentration*100).toFixed(0)}% of related department spend.` },
    { type:'purchase_pattern', label:'Purchase pattern', value:Math.min(1,clustered/1500000), confidence:clustered ? .88 : .70, evidenceId:'EV-SPLIT', detail:clustered ? `₹${clustered.toLocaleString('en-IN')} in related sub-threshold purchases observed in 14 days.` : 'No clustered sub-threshold purchases found.' },
    { type:'timing_anomaly', label:'Timing anomaly', value:tx.date.endsWith('-31') ? .8 : .18, confidence:.78, evidenceId:'EV-TIME', detail:'Timing compared with the fiscal-period baseline.' },
    { type:'approval_velocity', label:'Approval velocity', value:Math.min(1,Math.max(0,1-money(tx.approvalHours)/(.5*approvalMedian))), confidence:.82, evidenceId:'EV-VELOCITY', detail:`Approval completed in ${tx.approvalHours} hours compared with a ${approvalMedian.toFixed(0)} hour peer median.` },
  ];
};
const evaluate = tx => { const signals=signalsFor(tx); const confidence=signals.reduce((sum,item)=>sum+item.confidence,0)/signals.length; const score=Math.min(1,signals.reduce((sum,item)=>sum+WEIGHTS[item.type]*item.value,0)*confidence); const priority=Math.round(score*100); return { ...tx, vendorToken:vendorToken(tx.vendor), signals, risk:{ score, priority, confidenceFactor:Number(confidence.toFixed(2)), tier:score>=.75?'HIGH':score>=.4?'BORDERLINE':'LOW', weightsVersion:'v1.0' } }; };
const caseFor = tx => { const evaluated=evaluate(tx); const action=actions.filter(item=>item.transactionId===tx.id).at(-1); return { ...evaluated, caseId:`AUD-2026-${tx.id.replace('TX','')}`, status:action?.status || (evaluated.risk.tier==='HIGH'?'OPEN':'MONITORED'), assignedAuditorId:action?.actor || null, evidence:{ paymentDifference:money(tx.paymentAmount)-money(tx.invoiceAmount), peerMedian:median(transactions.filter(item=>item.id!==tx.id&&item.category===tx.category).map(item=>money(item.unitPrice))), policyCitations:['GFR-4.3','PROC-7.1'] } }; };
const requireAuth=(req,res,next)=>{const token=req.headers.authorization?.replace(/^Bearer\s+/,'');if(!token)return res.status(401).json({error:'Authentication required'});try{req.user=jwt.verify(token,SECRET);next()}catch{return res.status(401).json({error:'Invalid or expired session'})}};
const permit=permission=>(req,res,next)=>req.user.permissions.includes(permission)?next():res.status(403).json({error:'Missing required permission'});

app.disable('x-powered-by'); app.use(helmet({crossOriginResourcePolicy:false})); app.use(cors()); app.use(express.json({limit:'250kb'}));
app.get('/api/health', (_req,res)=>res.json({status:'ok', transactions:transactions.length, timestamp:new Date().toISOString()}));
app.post('/api/auth/login',(req,res)=>{const input=z.object({departmentId:z.string(),officerId:z.string(),password:z.string()}).safeParse(req.body);if(!input.success||Object.keys(credentials).some(key=>input.data?.[key]!==credentials[key]))return res.status(401).json({error:'The issued demo credentials were not recognised.'});const user={id:credentials.officerId.toLowerCase(),name:'A. Sharma',role:'Senior Audit Officer',permissions:['READ_MASKED','READ_BENCHMARK','READ_AUDIT','WRITE_EXECUTE','WRITE_UNMASK']};record(user.id,'AUTH_LOGIN',`USER-${user.id}`);res.json({accessToken:jwt.sign(user,SECRET,{expiresIn:'8h'}),user})});
app.get('/api/dashboard',requireAuth,permit('READ_MASKED'),(req,res)=>{const evaluated=transactions.map(evaluate);const cases=evaluated.filter(item=>item.risk.tier!=='LOW');record(req.user.id,'READ_DASHBOARD','DASHBOARD');res.json({data:{transactionsAnalysed:transactions.length,totalExpenditure:transactions.reduce((sum,tx)=>sum+money(tx.amount),0),casesRequiringReview:cases.length,reconciliationExceptions:transactions.filter(tx=>money(tx.paymentAmount)!==money(tx.invoiceAmount)).length,priorityDistribution:['LOW','BORDERLINE','HIGH'].map(tier=>({tier,count:evaluated.filter(item=>item.risk.tier===tier).length})),departmentSpending:Object.entries(transactions.reduce((all,tx)=>{all[tx.department]=(all[tx.department]||0)+money(tx.amount);return all},{})).map(([department,total])=>({department,total})).sort((a,b)=>b.total-a.total)}})});
app.get('/api/transactions',requireAuth,permit('READ_MASKED'),(req,res)=>{const q=(req.query.q||'').toString().toLowerCase();const data=transactions.filter(tx=>!q||[tx.id,tx.invoice,tx.vendor,tx.department].join(' ').toLowerCase().includes(q)).map(evaluate).sort((a,b)=>b.risk.priority-a.risk.priority);record(req.user.id,'READ_TRANSACTIONS','TRANSACTION_LIST',{count:data.length});res.json({data,total:data.length})});
app.post('/api/transactions',requireAuth,permit('WRITE_EXECUTE'),async(req,res)=>{const parsed=z.object({invoice:z.string(),contract:z.string(),date:z.string(),department:z.string(),vendor:z.string(),category:z.string(),region:z.string(),amount:z.number().positive(),invoiceAmount:z.number().positive(),paymentAmount:z.number().positive(),unitPrice:z.number().positive(),quantity:z.number().positive(),approvalHours:z.number().nonnegative()}).safeParse(req.body);if(!parsed.success)return res.status(400).json({error:'Complete canonical transaction fields are required.'});const id=`TX${String(10000+transactions.length+1)}`;const tx={id,...parsed.data,referenceGroup:`REF-${id}`};transactions.push(tx);await writeFile(DATA_FILE,JSON.stringify({generatedAt:new Date().toISOString(),transactions},null,2));record(req.user.id,'INGEST_TRANSACTION',id);res.status(201).json({data:caseFor(tx)})});
app.get('/api/cases',requireAuth,permit('READ_MASKED'),(req,res)=>{const data=transactions.map(caseFor).filter(item=>item.risk.tier!=='LOW').sort((a,b)=>b.risk.priority-a.risk.priority);record(req.user.id,'READ_CASE_QUEUE','CASE_QUEUE',{count:data.length});res.json({data,total:data.length})});
app.get('/api/cases/:id',requireAuth,permit('READ_MASKED'),(req,res)=>{const tx=transactions.find(item=>item.id===req.params.id||`AUD-2026-${item.id.replace('TX','')}`===req.params.id);if(!tx)return res.status(404).json({error:'Case not found'});const data=caseFor(tx);record(req.user.id,'READ_MASKED_CASE',data.caseId);res.json({data})});
app.post('/api/cases/:id/actions',requireAuth,permit('WRITE_EXECUTE'),async(req,res)=>{const input=z.object({action:z.enum(['APPROVE','REJECT','ESCALATE','RECALIBRATE']),justification:z.string().min(5).max(500)}).safeParse(req.body);const tx=transactions.find(item=>`AUD-2026-${item.id.replace('TX','')}`===req.params.id);if(!tx)return res.status(404).json({error:'Case not found'});if(!input.success)return res.status(400).json({error:'Valid action and justification are required.'});const status={APPROVE:'APPROVED',REJECT:'REJECTED',ESCALATE:'ESCALATED',RECALIBRATE:'IN_REVIEW'}[input.data.action];actions.push({id:crypto.randomUUID(),transactionId:tx.id,status,action:input.data.action,justification:input.data.justification,actor:req.user.id,createdAt:new Date().toISOString()});await persistActions();const log=record(req.user.id,`CASE_${input.data.action}`,tx.id,input.data);res.status(201).json({data:{case:caseFor(tx),auditId:log.id}})});
app.get('/api/vendors/:token/graph',requireAuth,permit('READ_MASKED'),(req,res)=>{const matching=transactions.filter(tx=>vendorToken(tx.vendor)===req.params.token);if(!matching.length)return res.status(404).json({error:'Vendor not found'});const nodes=[{id:req.params.token,type:'vendor',label:req.params.token},...new Map(matching.map(tx=>[tx.department,{id:tx.department,type:'department',label:tx.department}])).values()];const edges=matching.map(tx=>({source:tx.department,target:req.params.token,label:`₹${money(tx.amount).toLocaleString('en-IN')}`}));record(req.user.id,'READ_VENDOR_GRAPH',req.params.token);res.json({data:{nodes,edges}})});
app.post('/api/ai/explain',requireAuth,permit('READ_MASKED'),(req,res)=>{const tx=transactions.find(item=>item.id===req.body?.transactionId||item.id==='TX10291');if(!tx)return res.status(404).json({error:'Sufficient authorised evidence was not found.'});const item=caseFor(tx);const active=item.signals.filter(signal=>signal.value>=.4);record(req.user.id,'READ_GROUNDED_EXPLANATION',tx.id);res.json({data:{rationale:active.length?`${tx.id} received an Audit Priority Score of ${item.risk.priority} because ${active.map(signal=>signal.detail).join(' ')} The system recommends review; it does not determine fraud or wrongdoing.`:'No material evidence meets the configured review threshold.',groundingRate:1,citations:active.map(signal=>({evidenceId:signal.evidenceId,policyId:'GFR-4.3'}))}})});
app.get('/api/audit-log',requireAuth,permit('READ_AUDIT'),(_req,res)=>res.json({data:audit}));

await load();
if(process.argv[1]?.endsWith('index.js'))app.listen(PORT,()=>console.log(`GovSpend API running at http://localhost:${PORT}`));
export {app,evaluate,signalsFor};
